/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import DataClasses.DataExpediente;
import static DataClasses.DataListaExpedientes.listaExpedientes;
import javax.swing.table.DefaultTableModel;
import tda.NodoDoble;
import static DataManagers.ListaExpedientesManager.*;
import DataManagers.ListaTramitesPendientes;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author MARIEL
 */
public class AdminScreen extends javax.swing.JFrame {

private DefaultTableModel modelo;

private Timer alertaTimer;
private boolean alertaMostrada = false;
    
    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        this.modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        
        initComponents();
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRES");
        modelo.addColumn("DNI");
        modelo.addColumn("TIPO");
        modelo.addColumn("PRIORIDAD");
        this.tablaExp.setModel(modelo);
        this.tablaExp.getColumnModel().getColumn(0).setPreferredWidth(60);

        if (!listaExpedientes.esVacia()) {
            Poblar();
        }
        
        ListaTramitesPendientes.actualizarTramitesPendientes();
    }
    
    private void iniciarAlertaPendientesTimer() {
        if (alertaTimer != null && alertaTimer.isRunning()) {
            alertaTimer.stop();
        }
        
        alertaTimer = new Timer(30000, e -> {
            if (!alertaMostrada) {
                ListaTramitesPendientes.actualizarTramitesPendientes();
                
                if (ListaTramitesPendientes.hayPendientes()) {
                    new AlertaPendientesDialog(this, true).setVisible(true);
                }
                
                alertaMostrada = true;
            }
            
            alertaTimer.stop();
        });
        
        alertaTimer.setRepeats(false);
        alertaTimer.start();
    }

    private void Poblar()
    {
        int filas = this.tablaExp.getRowCount();
        for(int i=0;i<filas;i++)
        {
            modelo.removeRow(0);
        }
        
       NodoDoble<DataExpediente> nodoAux = listaExpedientes.getCabeza();
       String[] datos = new String[5];
       
       for(int i = 0; i < listaExpedientes.longitud(); i++)
       {
           datos[0] = String.valueOf(nodoAux.getItem().getId());
           datos[1] = String.valueOf(nodoAux.getItem().getNombres());
           datos[2] = String.valueOf(nodoAux.getItem().getDni());
           datos[3] = String.valueOf(nodoAux.getItem().getTipo());
           datos[4] = String.valueOf(nodoAux.getItem().getPrioridad());
           modelo.addRow(datos);
           nodoAux = nodoAux.getSgteNodo();
       }
    }    
    
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            alertaMostrada = false;
            iniciarAlertaPendientesTimer();
        } else {
            if (alertaTimer != null && alertaTimer.isRunning()) {
                alertaTimer.stop();
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fin_sesion_boton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dni_txtField = new javax.swing.JTextField();
        buscarExp_boton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaExp = new javax.swing.JTable();
        ingresarExp_boton = new javax.swing.JButton();
        bienvenidoUser_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        fin_sesion_boton.setText("CERRAR SESION");
        fin_sesion_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fin_sesion_botonActionPerformed(evt);
            }
        });

        jLabel1.setText("DNI: ");

        dni_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dni_txtFieldActionPerformed(evt);
            }
        });

        buscarExp_boton.setText("BUSCAR EXPEDIENTE");
        buscarExp_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarExp_botonActionPerformed(evt);
            }
        });

        tablaExp.setAutoCreateRowSorter(true);
        tablaExp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaExp.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tablaExp.setAutoscrolls(false);
        tablaExp.setCellSelectionEnabled(true);
        tablaExp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaExp.setFillsViewportHeight(true);
        tablaExp.setShowGrid(false);
        tablaExp.setShowVerticalLines(true);
        tablaExp.getTableHeader().setResizingAllowed(false);
        tablaExp.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaExp);

        ingresarExp_boton.setText("INGRESAR EXPEDIENTE");
        ingresarExp_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarExp_botonActionPerformed(evt);
            }
        });

        bienvenidoUser_label.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bienvenidoUser_label.setText("BIENVENIDO, admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fin_sesion_boton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bienvenidoUser_label)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dni_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarExp_boton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ingresarExp_boton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(bienvenidoUser_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresarExp_boton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(dni_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarExp_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(fin_sesion_boton)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fin_sesion_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fin_sesion_botonActionPerformed
        ScreensManager.irAtras(this);
    }//GEN-LAST:event_fin_sesion_botonActionPerformed

    private void ingresarExp_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarExp_botonActionPerformed
        IngresarExpScreen ingresarExp_pantalla = new IngresarExpScreen();
        ScreensManager.nuevaPantalla(this, ingresarExp_pantalla);
    }//GEN-LAST:event_ingresarExp_botonActionPerformed

    private void buscarExp_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarExp_botonActionPerformed
        try {

            if (dni_txtField.getText().length() != 8) {
                JOptionPane.showMessageDialog(rootPane, "DNI no es válido.", "Error", JOptionPane.WARNING_MESSAGE);
                dni_txtField.setText("");
                return;
            }            
            
            int dni = Integer.parseInt(dni_txtField.getText().trim());
            DataExpediente exp;
            exp = buscarExpediente(dni);

            if (exp != null) {
                dni_txtField.setText("");
                ExpedienteBuscadoScreen exBuscado_pantalla = new ExpedienteBuscadoScreen(exp);
                ScreensManager.nuevaPantalla(this, exBuscado_pantalla);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "DNI no encontrado.", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
                dni_txtField.setText("");
            }
        
        } 
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "DNI no es válido.", "Error", JOptionPane.WARNING_MESSAGE);
            dni_txtField.setText("");
        }        
    }//GEN-LAST:event_buscarExp_botonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        Poblar();
        
        if (!isDialogEvent(evt)) {
            iniciarAlertaPendientesTimer();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void dni_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dni_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dni_txtFieldActionPerformed

    private boolean isDialogEvent(WindowEvent evt) {
        return evt.getOppositeWindow() instanceof javax.swing.JDialog;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidoUser_label;
    private javax.swing.JButton buscarExp_boton;
    private javax.swing.JTextField dni_txtField;
    private javax.swing.JButton fin_sesion_boton;
    private javax.swing.JButton ingresarExp_boton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaExp;
    // End of variables declaration//GEN-END:variables
}
