/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;
import DataClasses.*;
import DataManagers.ExpedienteManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tda.*;
/**
 *
 * @author MARIEL
 */
public class ExpedienteBuscadoScreen extends javax.swing.JFrame {
    /**
     * Creates new form ExpedienteBuscadoScreen
     * @param exp
     */
    private DefaultTableModel modelo_1;
    private DefaultTableModel modelo_2;
    private DataExpediente expediente;
    public ExpedienteBuscadoScreen(DataExpediente exp) {
        initComponents();
        this.expediente = exp;
        id_label.setText("ID: "+expediente.getId());
        prioridad_label.setText("PRIORIDAD: " + expediente.getPrioridad());
        nombres_label.setText("NOMBRES: "+expediente.getNombres());
        tipo_label.setText("TIPO: "+expediente.getTipo());
        telefono_label.setText("TELEFONO: "+expediente.getTelefono());
        email_label.setText("EMAIL: : "+expediente.getEmail());
        
        
        modelo_1 = new DefaultTableModel();
        modelo_1.addColumn("NRO");
        modelo_1.addColumn("NOMBRE DEL DOCUMENTO");
        
        modelo_2 = new DefaultTableModel();
        modelo_2.addColumn("ID");
        modelo_2.addColumn("DESCRIPCION");
        modelo_2.addColumn("FECHA DE INICIO");
        
        this.docsTabla.setModel(modelo_1);
        this.tramitesTabla.setModel(modelo_2);     
        
        
    }
    
    private void poblarDocsTable(){
        int filas = this.docsTabla.getRowCount();
        for(int i=0;i<filas;i++)
        {
            modelo_1.removeRow(0);
        }
        
        Cola<Documento> cola = ExpedienteManager.mostrarDocumentos(expediente);
        Cola<Documento> aux = new Cola<>();
        String[] datos = new String[2];

        int conta = 1;
        while (!cola.esVacia()){
            Documento doc = cola.desencolar();
            datos[0] = conta+"";
            datos[1] = doc.getItem();
            modelo_1.addRow(datos);
            conta++;
            aux.encolar(doc);
        }
        
        while (!aux.esVacia()){
            cola.encolar(aux.desencolar());
        }
    }
    
    private void poblarTramTable(){
        int filas = this.tramitesTabla.getRowCount();
        for(int i=0;i<filas;i++)
        {
            modelo_2.removeRow(0);
        }
        
        Lista<DataTramite> lista = ExpedienteManager.mostrarTramites(expediente);
        Nodo<DataTramite> aux = lista.getCabeza();

        for (int i = 0; i < lista.longitud(); i++) {
            DataTramite temp = aux.getItem();
            modelo_2.addRow(new Object[] {temp.getId(), temp.getDescripcion(), temp.getFechaIni()});
            aux = aux.getSgteNodo();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        id_label = new javax.swing.JLabel();
        prioridad_label = new javax.swing.JLabel();
        nombres_label = new javax.swing.JLabel();
        tipo_label = new javax.swing.JLabel();
        telefono_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        docsTabla = new javax.swing.JTable();
        addDoc_botton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tramitesTabla = new javax.swing.JTable();
        addTram_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        id_txtField = new javax.swing.JTextField();
        accTram_boton = new javax.swing.JButton();
        actualizar_boton = new javax.swing.JButton();
        atras_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(850, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 500));

        id_label.setText("ID:");

        prioridad_label.setText("PRIORIDAD:");

        nombres_label.setText("NOMBRES:");

        tipo_label.setText("TIPO: ");

        telefono_label.setText("TELEFONO: ");

        email_label.setText("EMAIL:");

        docsTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(docsTabla);

        addDoc_botton.setText("AGREGAR DOCUMENTO");
        addDoc_botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoc_bottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDoc_botton)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(email_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(telefono_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addComponent(tipo_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombres_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(prioridad_label, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(id_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prioridad_label)
                .addGap(11, 11, 11)
                .addComponent(nombres_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipo_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telefono_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email_label)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addDoc_botton)
                .addGap(22, 22, 22))
        );

        addDoc_botton.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("DATOS DEL EXPEDIENTE", jPanel1);

        tramitesTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tramitesTabla);

        jScrollPane2.setViewportView(jScrollPane1);

        addTram_button.setText("AÑADIR TRAMITE");
        addTram_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTram_buttonActionPerformed(evt);
            }
        });

        jLabel8.setText("ID: ");

        accTram_boton.setText("ACCEDER A TRAMITE");
        accTram_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accTram_botonActionPerformed(evt);
            }
        });

        actualizar_boton.setText("ACTUALIZAR");
        actualizar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(actualizar_boton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(addTram_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accTram_boton)
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(actualizar_boton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTram_button)
                    .addComponent(id_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(accTram_boton))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TRAMITES DEL EXPEDIENTE", jPanel2);

        atras_button.setText("REGRESAR");
        atras_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(atras_button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(atras_button)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addTram_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTram_buttonActionPerformed
        IngresarTramScreen ingresarTram_pantalla = new IngresarTramScreen(expediente);
        ScreensManager.nuevaPantalla(this, ingresarTram_pantalla);
    }//GEN-LAST:event_addTram_buttonActionPerformed

    private void atras_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras_buttonActionPerformed
        ScreensManager.irAtras(this);
    }//GEN-LAST:event_atras_buttonActionPerformed

    private void accTram_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accTram_botonActionPerformed
        TramiteBuscadoScreen tramiteBuscado_pantalla = new TramiteBuscadoScreen(expediente);
        ScreensManager.nuevaPantalla(this, tramiteBuscado_pantalla);
    }//GEN-LAST:event_accTram_botonActionPerformed

    private void addDoc_bottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoc_bottonActionPerformed
        String nombre_doc = JOptionPane.showInputDialog(this, "Ingrese el nombre del documento");
        Documento aux = new Documento(nombre_doc);
        ExpedienteManager.agregarDocumento(expediente, aux);
        JOptionPane.showMessageDialog(this, "Documento ingresado");
        poblarDocsTable();
    }//GEN-LAST:event_addDoc_bottonActionPerformed

    private void actualizar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_botonActionPerformed
        poblarTramTable();
    }//GEN-LAST:event_actualizar_botonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpedienteBuscadoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpedienteBuscadoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpedienteBuscadoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpedienteBuscadoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DataExpediente aux = new DataExpediente(0, 0000, "NULL", "NULL", 0, "NULL");
                new ExpedienteBuscadoScreen(aux).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accTram_boton;
    private javax.swing.JButton actualizar_boton;
    private javax.swing.JButton addDoc_botton;
    private javax.swing.JButton addTram_button;
    private javax.swing.JButton atras_button;
    private javax.swing.JTable docsTabla;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_txtField;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nombres_label;
    private javax.swing.JLabel prioridad_label;
    private javax.swing.JLabel telefono_label;
    private javax.swing.JLabel tipo_label;
    private javax.swing.JTable tramitesTabla;
    // End of variables declaration//GEN-END:variables
}
