/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import DataClasses.DataExpediente;
import DataManagers.ListaExpedientesManager;
import static DataManagers.ListaExpedientesManager.agregarExpediente;
import javax.swing.JOptionPane;

/**
 *
 * @author MARIEL
 */
public class IngresarExpScreen extends javax.swing.JFrame {

    /**
     * Creates new form IngresarExpScreen
     */
    public IngresarExpScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGroup_tipo = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        prioridad_comboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dni_txtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombres_txtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefono_txtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email_txtField = new javax.swing.JTextField();
        tipoExterno_radioBoton = new javax.swing.JRadioButton();
        tipoULIMA_radioBoton = new javax.swing.JRadioButton();
        cancel_boton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        listo_boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar Expediente");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        setIconImages(null);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 159, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(239, 241, 243));
        jLabel7.setText("INGRESAR EXPEDIENTE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 56, 67));
        jLabel1.setText("PRIORIDAD:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 22));

        prioridad_comboBox.setBackground(new java.awt.Color(239, 241, 243));
        prioridad_comboBox.setForeground(new java.awt.Color(34, 56, 67));
        prioridad_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(prioridad_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 56, 67));
        jLabel2.setText("DNI: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 37, -1));

        dni_txtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dni_txtField.setForeground(new java.awt.Color(34, 56, 67));
        dni_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dni_txtFieldFocusLost(evt);
            }
        });
        dni_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dni_txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dni_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 56, 67));
        jLabel3.setText("NOMBRES:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        nombres_txtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nombres_txtField.setForeground(new java.awt.Color(34, 56, 67));
        jPanel1.add(nombres_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 170, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 56, 67));
        jLabel4.setText("TELEFONO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        telefono_txtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        telefono_txtField.setForeground(new java.awt.Color(34, 56, 67));
        telefono_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefono_txtFieldFocusLost(evt);
            }
        });
        telefono_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(telefono_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 170, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 56, 67));
        jLabel5.setText("EMAIL:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        email_txtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        email_txtField.setForeground(new java.awt.Color(34, 56, 67));
        email_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(email_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 170, -1));

        botonGroup_tipo.add(tipoExterno_radioBoton);
        tipoExterno_radioBoton.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        tipoExterno_radioBoton.setForeground(new java.awt.Color(34, 56, 67));
        tipoExterno_radioBoton.setText("Usuario Externo");
        tipoExterno_radioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoExterno_radioBotonActionPerformed(evt);
            }
        });
        jPanel1.add(tipoExterno_radioBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 140, -1));

        botonGroup_tipo.add(tipoULIMA_radioBoton);
        tipoULIMA_radioBoton.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        tipoULIMA_radioBoton.setForeground(new java.awt.Color(34, 56, 67));
        tipoULIMA_radioBoton.setText("Usuario ULIMA");
        jPanel1.add(tipoULIMA_radioBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 112, -1));

        cancel_boton.setBackground(new java.awt.Color(239, 241, 243));
        cancel_boton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cancel_boton.setForeground(new java.awt.Color(34, 56, 67));
        cancel_boton.setText("CANCELAR");
        cancel_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_botonActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 140, -1));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 500));

        jPanel2.setBackground(new java.awt.Color(34, 56, 67));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(239, 241, 243));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 20, 500));

        listo_boton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        listo_boton.setForeground(new java.awt.Color(34, 56, 67));
        listo_boton.setText("LISTO");
        listo_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listo_botonActionPerformed(evt);
            }
        });
        jPanel2.add(listo_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 140, -1));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 210, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telefono_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_txtFieldActionPerformed

    private void email_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtFieldActionPerformed

    private void tipoExterno_radioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoExterno_radioBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoExterno_radioBotonActionPerformed

    private void cancel_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_botonActionPerformed
        int btnRegresar = JOptionPane.showConfirmDialog(rootPane, "¿Desea regresar?\nTodo su progreso se perderá.", "Confirmación", 0);
        if (btnRegresar == 0) {
            ScreensManager.irAtras(this);        
        }
        
    }//GEN-LAST:event_cancel_botonActionPerformed

    private void listo_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listo_botonActionPerformed
        int prioridad = Integer.parseInt(prioridad_comboBox.getSelectedItem().toString());
        String tipoUsuario;
        if (dni_txtField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese el DNI.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;        
        }
        if (nombres_txtField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese los nombres.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;        
        }
        if (telefono_txtField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese el número de teléfono.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;        
        }
        if (email_txtField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese el correo electronico.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;        
        }        
        if (tipoULIMA_radioBoton.isSelected()) {
            tipoUsuario = "ULIMA";
        }
        else if (tipoExterno_radioBoton.isSelected()){
            tipoUsuario = "EXTERNO";
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Escoge el tipo de usuario.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DataExpediente aux = new DataExpediente(prioridad, Integer.parseInt(dni_txtField.getText().trim()), nombres_txtField.getText().trim(), tipoUsuario, Integer.parseInt(telefono_txtField.getText().trim()), email_txtField.getText().trim());    
        agregarExpediente(aux);
        JOptionPane.showMessageDialog(rootPane, "Expediente ingresado correctamente.", "Correcto", JOptionPane.INFORMATION_MESSAGE);
        ScreensManager.irAtras(this);
    }//GEN-LAST:event_listo_botonActionPerformed

    private void dni_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dni_txtFieldActionPerformed

    }//GEN-LAST:event_dni_txtFieldActionPerformed

    private void dni_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dni_txtFieldFocusLost
        if (dni_txtField.getText().length() != 8) {
            JOptionPane.showMessageDialog(rootPane, "DNI no es válido.", "Error", JOptionPane.WARNING_MESSAGE);
            dni_txtField.setText("");
        }
        if (ListaExpedientesManager.buscarExpediente(Integer.parseInt(dni_txtField.getText().trim())) != null) {
            JOptionPane.showMessageDialog(rootPane, "El DNI ya fue ingresado anteriormente.\nRevisar lista de expedientes.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            dni_txtField.setText("");
        }        
        else {
            try {
                int dni = Integer.parseInt(dni_txtField.getText().trim());
            }
            catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "DNI no es válido.", "Error", JOptionPane.WARNING_MESSAGE);
                dni_txtField.setText("");
            }
        }
    }//GEN-LAST:event_dni_txtFieldFocusLost

    private void telefono_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefono_txtFieldFocusLost
        if (telefono_txtField.getText().length() != 9) {
            JOptionPane.showMessageDialog(rootPane, "Telefono no es válido.", "Error", JOptionPane.WARNING_MESSAGE);
            telefono_txtField.setText("");
        }
        else {
            try {
                int telefono = Integer.parseInt(telefono_txtField.getText().trim());
            }
            catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "Telefono no es válido.", "Error", JOptionPane.WARNING_MESSAGE);
                telefono_txtField.setText("");
            }
        }
    }//GEN-LAST:event_telefono_txtFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarExpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarExpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarExpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarExpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarExpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.ButtonGroup botonGroup_tipo;
    private javax.swing.JButton cancel_boton;
    private javax.swing.JTextField dni_txtField;
    private javax.swing.JTextField email_txtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton listo_boton;
    private javax.swing.JTextField nombres_txtField;
    private javax.swing.JComboBox<String> prioridad_comboBox;
    private javax.swing.JTextField telefono_txtField;
    private javax.swing.JRadioButton tipoExterno_radioBoton;
    private javax.swing.JRadioButton tipoULIMA_radioBoton;
    // End of variables declaration//GEN-END:variables
}
