/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import DataClasses.DataExpediente;
import DataClasses.DataListaDependencias;
import DataClasses.DataTramite;
import DataClasses.Dependencia;
import DataClasses.Fecha;
import DataManagers.ExpedienteManager;
import DataManagers.ListaDependenciasManager;
import static java.lang.String.valueOf;
import java.util.Calendar;
import static java.util.Calendar.DATE;
import static java.util.Calendar.MONTH;
import static java.util.Calendar.YEAR;
import java.util.GregorianCalendar;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import tda.Lista;
import tda.Nodo;
import tda.Pila;

/**
 *
 * @author MARIEL
 */
public class IngresarTramScreen extends javax.swing.JFrame {

    /**
     * Creates new form IngresarTramScreen
     */
    private DataExpediente expediente;
    public IngresarTramScreen(DataExpediente exp) {
        initComponents();
        ListaDependenciasManager.inicializar();
        
        this.expediente = exp;
        dni_label.setText("DNI: "+expediente.getDni());
        nombre_txtLabel.setText("NOMBRES: "+expediente.getNombres());
        
        Calendar calendar = new GregorianCalendar();
        dia_txtField.setText(String.valueOf( calendar.get(DATE)));
        mes_txtField.setText(String.valueOf(calendar.get(MONTH)+1));
        annio_txtField.setText(String.valueOf(calendar.get(YEAR)));
        
        actualizarDepends();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre_txtLabel = new javax.swing.JLabel();
        dni_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dia_txtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        annio_txtField = new javax.swing.JTextField();
        mes_txtField = new javax.swing.JTextField();
        dependencias_comboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        listo_boton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc_txtArea = new javax.swing.JTextArea();
        regresar_boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 500));
        setPreferredSize(new java.awt.Dimension(850, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 500));

        jPanel1.setBackground(new java.awt.Color(255, 159, 28));
        jPanel1.setForeground(new java.awt.Color(34, 56, 67));
        jPanel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre_txtLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nombre_txtLabel.setForeground(new java.awt.Color(34, 56, 67));
        nombre_txtLabel.setText("NOMBRE: ");
        jPanel1.add(nombre_txtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, -1));

        dni_label.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dni_label.setForeground(new java.awt.Color(34, 56, 67));
        dni_label.setText("DNI: ########");
        jPanel1.add(dni_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 56, 67));
        jLabel4.setText("DEPENDENCIA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 105, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 56, 67));
        jLabel1.setText("FECHA DE INICIO (DD/MM/AAAA):");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        dia_txtField.setBackground(new java.awt.Color(239, 241, 243));
        dia_txtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dia_txtField.setForeground(new java.awt.Color(34, 56, 67));
        dia_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia_txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dia_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 40, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 56, 67));
        jLabel2.setText("DESCRIPCION:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 186, -1));

        annio_txtField.setBackground(new java.awt.Color(239, 241, 243));
        annio_txtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        annio_txtField.setForeground(new java.awt.Color(34, 56, 67));
        annio_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annio_txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(annio_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 60, -1));

        mes_txtField.setBackground(new java.awt.Color(239, 241, 243));
        mes_txtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mes_txtField.setForeground(new java.awt.Color(34, 56, 67));
        jPanel1.add(mes_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 40, -1));

        dependencias_comboBox.setBackground(new java.awt.Color(239, 241, 243));
        dependencias_comboBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dependencias_comboBox.setForeground(new java.awt.Color(34, 56, 67));
        dependencias_comboBox.setModel(dependencias_comboBox.getModel());
        dependencias_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dependencias_comboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(dependencias_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(34, 56, 67));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listo_boton.setBackground(new java.awt.Color(239, 241, 243));
        listo_boton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        listo_boton.setForeground(new java.awt.Color(34, 56, 67));
        listo_boton.setText("LISTO");
        listo_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listo_botonActionPerformed(evt);
            }
        });
        jPanel2.add(listo_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 210, 510));

        jPanel3.setBackground(new java.awt.Color(239, 241, 243));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 10, 510));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 241, 243));
        jLabel3.setText("INGRESAR TRAMITE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        desc_txtArea.setBackground(new java.awt.Color(239, 241, 243));
        desc_txtArea.setColumns(20);
        desc_txtArea.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        desc_txtArea.setForeground(new java.awt.Color(34, 56, 67));
        desc_txtArea.setRows(5);
        jScrollPane1.setViewportView(desc_txtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 340, -1));

        regresar_boton.setBackground(new java.awt.Color(239, 241, 243));
        regresar_boton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        regresar_boton.setForeground(new java.awt.Color(34, 56, 67));
        regresar_boton.setText("CANCELAR");
        regresar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_botonActionPerformed(evt);
            }
        });
        jPanel1.add(regresar_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarDepends(){
        Lista<Dependencia> lista = DataListaDependencias.listaDependenciasGlobal;
        Nodo<Dependencia> aux_nodo = lista.getCabeza();
        JComboBox<String> aux = new JComboBox();
        
        //vaciar modelo
        aux.removeAllItems();
        //volver a llenar
        while (aux_nodo != null) {
            aux.addItem(aux_nodo.getItem().getNombre());
            aux_nodo = aux_nodo.getSgteNodo();
        }
        
        dependencias_comboBox.setModel(aux.getModel());
    }
    private void regresar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_botonActionPerformed

        int response = JOptionPane.showConfirmDialog(rootPane, "¿Desea regresar? Todo su progreso se perderá", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            dia_txtField.setText("");
            mes_txtField.setText("");
            annio_txtField.setText("");
            ScreensManager.irAtras(this);
        }
        else{
            //no hacer nada
        }

    }//GEN-LAST:event_regresar_botonActionPerformed

    private void listo_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listo_botonActionPerformed
        String diaStr = dia_txtField.getText().trim();
        String mesStr = mes_txtField.getText().trim();
        String annioStr = annio_txtField.getText().trim();
        String desc = desc_txtArea.getText().trim();
        String depend = dependencias_comboBox.getSelectedItem().toString();
        Pila<String> aux = new Pila<>();
        aux.apilar(depend);
        

        // Evitar campos vacios
        if (diaStr.isEmpty() || mesStr.isEmpty() || annioStr.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        // Verificar contenido numerico
        int dia, mes, annio;
        
        try {
            dia = Integer.parseInt(diaStr);
            mes = Integer.parseInt(mesStr);
            annio = Integer.parseInt(annioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe contener solo numeros.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        Calendar calendar = new GregorianCalendar();
        int cal1 = calendar.get(YEAR);
        int cal2 = calendar.get(MONTH);
        int cal3 = calendar.get(DATE);        
        
        // Fecha ingresada no puede ser mayor a la actual (dia de hoy)
        if (annio == cal1) {
            if (mes > cal2 && dia > cal3) {
                JOptionPane.showMessageDialog(this, "Ingrese una fecha valida antes de la fecha actual.", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
        }
        
        // Validar rangos de fecha
        if (dia < 1 || dia > 31 || mes < 1 || mes > 12 || annio < 1900 || annio > cal1) {
            JOptionPane.showMessageDialog(this, "Ingrese una fecha valida en formato DD/MM/AAAA.", "Error", JOptionPane.ERROR_MESSAGE);
            return;   
        }

        // Validar descripcion
        if (desc.isBlank()) {
            JOptionPane.showMessageDialog(this, "La descripcion no puede estar en blanco.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        // Validar si se pone otra dependencia
        if (depend.equals("Otro")) {
            String nom_depend = JOptionPane.showInputDialog(this, "Ingrese el nombre de la nueva dependencia.");
            
            if (nom_depend == null) {
                return;
            }
            else if (nom_depend.isBlank()) {
                    JOptionPane.showMessageDialog(this, "Nombre de dependencia no puede estar vacío.", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
            }
            else{
                Dependencia depend_nueva = new Dependencia(nom_depend);
                boolean duplicado = ListaDependenciasManager.duplicado(depend_nueva);
                if (!duplicado) {
                    ListaDependenciasManager.agregarDependencia(depend_nueva);
                    JOptionPane.showMessageDialog(this, "Se agregó la dependencia global.");
                    actualizarDepends();
                    return;
                    
                    //se agrego la dependencia correctamente
                }
                else{
                    JOptionPane.showMessageDialog(this, "La dependencia ingresada ya existe!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }
        // Realizar el ingreso del tramite
        Fecha fechaIni = new Fecha(dia, mes, annio);
        int numTramites = expediente.getListaTramites().longitud()+1;
        Dependencia dependInicial = new Dependencia(depend);
        DataTramite tramite = new DataTramite(fechaIni, desc, dependInicial, numTramites);
        ExpedienteManager.agregarTramite(expediente, tramite);
        
        JOptionPane.showMessageDialog(this, "Tramite ingresado correctamente.");
        ScreensManager.irAtras(this);
    }//GEN-LAST:event_listo_botonActionPerformed

    private void dependencias_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dependencias_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dependencias_comboBoxActionPerformed

    private void dia_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dia_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dia_txtFieldActionPerformed

    private void annio_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annio_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annio_txtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarTramScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarTramScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarTramScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarTramScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DataExpediente aux = new DataExpediente(0, 0000, "NULL", "NULL", 0, "NULL");
                new IngresarTramScreen(aux).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annio_txtField;
    private javax.swing.JComboBox<String> dependencias_comboBox;
    private javax.swing.JTextArea desc_txtArea;
    private javax.swing.JTextField dia_txtField;
    private javax.swing.JLabel dni_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listo_boton;
    private javax.swing.JTextField mes_txtField;
    private javax.swing.JLabel nombre_txtLabel;
    private javax.swing.JButton regresar_boton;
    // End of variables declaration//GEN-END:variables
}
