/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import DataClasses.DataExpediente;
import javax.swing.JOptionPane;

/**
 *
 * @author MARIEL
 */
public class IngresarExpScreen extends javax.swing.JFrame {

    /**
     * Creates new form IngresarExpScreen
     */
    public IngresarExpScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGroup_tipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        prioridad_comboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dni_txtField = new javax.swing.JTextField();
        nombres_txtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefono_txtField = new javax.swing.JTextField();
        email_txtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipoULIMA_radioBoton = new javax.swing.JRadioButton();
        tipoExterno_radioBoton = new javax.swing.JRadioButton();
        listo_boton = new javax.swing.JButton();
        cancel_boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar Expediente");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(850, 500));
        setPreferredSize(new java.awt.Dimension(850, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PRIORIDAD:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 83, 22));

        prioridad_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        prioridad_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioridad_comboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(prioridad_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, 22));

        jLabel2.setText("DNI: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 37, -1));
        getContentPane().add(dni_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, -1));
        getContentPane().add(nombres_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 140, -1));

        jLabel3.setText("NOMBRES:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        telefono_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_txtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(telefono_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, -1));

        email_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(email_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 140, -1));

        jLabel4.setText("TELEFONO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setText("EMAIL:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel7.setText("INGRESAR EXPEDIENTE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 146, -1));

        botonGroup_tipo.add(tipoULIMA_radioBoton);
        tipoULIMA_radioBoton.setText("Usuario ULIMA");
        getContentPane().add(tipoULIMA_radioBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 112, -1));

        botonGroup_tipo.add(tipoExterno_radioBoton);
        tipoExterno_radioBoton.setText("Usuario externo");
        tipoExterno_radioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoExterno_radioBotonActionPerformed(evt);
            }
        });
        getContentPane().add(tipoExterno_radioBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 112, -1));

        listo_boton.setText("LISTO");
        listo_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listo_botonActionPerformed(evt);
            }
        });
        getContentPane().add(listo_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        cancel_boton.setText("CANCELAR");
        cancel_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_botonActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telefono_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_txtFieldActionPerformed

    private void email_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtFieldActionPerformed

    private void tipoExterno_radioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoExterno_radioBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoExterno_radioBotonActionPerformed

    private void cancel_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_botonActionPerformed
        int btnRegresar = JOptionPane.showConfirmDialog(rootPane, "Estás seguro de regresar?\nPerderás todo tu progreso.", "Advertencia", 0);
        if (btnRegresar == 0) {
            ScreensManager.irAtras(this);        
        }
        
    }//GEN-LAST:event_cancel_botonActionPerformed

    private void listo_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listo_botonActionPerformed

        JOptionPane.showMessageDialog(rootPane, "Expediente ingresado correctamente");
        ScreensManager.irAtras(this);
    }//GEN-LAST:event_listo_botonActionPerformed

    private void prioridad_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioridad_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prioridad_comboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarExpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarExpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarExpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarExpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarExpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonGroup_tipo;
    private javax.swing.JButton cancel_boton;
    private javax.swing.JTextField dni_txtField;
    private javax.swing.JTextField email_txtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton listo_boton;
    private javax.swing.JTextField nombres_txtField;
    private javax.swing.JComboBox<String> prioridad_comboBox;
    private javax.swing.JTextField telefono_txtField;
    private javax.swing.JRadioButton tipoExterno_radioBoton;
    private javax.swing.JRadioButton tipoULIMA_radioBoton;
    // End of variables declaration//GEN-END:variables
}
